K [create storage account] **************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: msrest.exceptions.AuthenticationError: , ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f19491f0d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ueqlZ6/ansible_module_azure_rm_storageaccount.py\", line 462, in <module>\n    main()\n  File \"/tmp/ansible_ueqlZ6/ansible_module_azure_rm_storageaccount.py\", line 459, in main\n    AzureRMStorageAccount()\n  File \"/tmp/ansible_ueqlZ6/ansible_module_azure_rm_storageaccount.py\", line 201, in __init__\n    supports_check_mode=True)\n  File \"/tmp/ansible_ueqlZ6/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 323, in __init__\n  File \"/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py\", line 448, in __init__\n    self.set_token()\n  File \"/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py\", line 482, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/usr/local/lib/python2.7/dist-packages/msrest/exceptions.py\", line 48, in raise_with_traceback\n    raise error\nmsrest.exceptions.AuthenticationError: , ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f19491f0d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/fred/task/storageaccount.retry

PLAY RECAP *********************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1 
